
```{r, include=FALSE, warning=FALSE, message=FALSE}

library(tidyverse)
library(kableExtra)

```

# Introduction {#intro}


This chapter introduces the book and describes in more detail some of the tools that the book features. Chapter 2 provides an overview of errors in surveying, and gives some practical examples of how to prevent them. Chapter 3 touches on sampling methods in programs and evaluations, with a case study example provided. Chapter 4 

## What is a survey? {#surveydef}

In their comprehensive work on survey methodology, @groves2009 describe surveys in a similar way as used in other social sciences, including evaluation. They describe surveys as: i) gathering information primarily by asking people questions; collecting information by having interviewers ask questions and record answers, or by having people read/hear questions and record their own answers; and that information is collected from a subset of the population (a sample) (p. 27).  

This understanding of surveys has two fundamental premises. First, that the survey process is "that by describing the sample of people who actually respond, one can describe the target population" and second, "that the answers people give can be used to accurately describe characteristics of the respondents" [@fowler2014].  

Surveys in this regard are more than the data collection instrument, but rather are a systematic approach to data collection and analysis, @pfl1 describes them as "a comprehensive system for collecting information to describe, compare or explain knowledge, attitudes and behaviour", the comprehensiveness including the consideration of errors, sampling techniques, analysis methods, reporting, etc.  

These definitions suit the purpose of this book, and I feel adequately describe surveying as a data collection tool used in evaluation.  
### Survey Components



Some researchers understand effective survey design to be rooted in following a sequence of steps, for example, @pfl1 identify 10 steps in the surveying process:  
1. Setting specific, measurable objectives  
2. Planning and scheduling the survey  
3. Ensuring that appropriate resources are available  
4. Designing the survey  
5. Preparing the data collection instrument   
6. Validating the instrument  
7. Selecting participants  
8. Administering and scoring the instrument  
9. Analyzing the data  
10. Reporting the results.    

@glasow2005 similarly defines four steps in the survey process: survey design (sample selection, sample size, survey instrument selection), survey instrument development, survey execution, and data analysis and reporting survey results (also see @moll2016 for a meta-review of other suggested survey processes).  

While these approaches are intuitive and practical

As early as 1998, @groves2009 began to depart from the idea that "if step-by-step instructions were followed, high quality would be guaranteed" from surveys, and instead see surveys as "requiring the implementation of principles in unique ways to fit a particular substantive purpose for a particular target population" [@groves2009, 17]. I feel that this methodological approach is better suited to non-

@fowler2014 identifies three methodologies within the survey itself: sampling, question design, interviewing (when applicable), and the mode of data collection, which when combined with the decision-making necessary in each component, comprise what he calls *total survey design*. 







## Prerequisite tools used and skills required

To make the most of this book, it's recommended that you have a working knowledge of the R programming language, and have some experience with digital surveying instruments such as SurveyMonkey or Limesurvey. That being said, there is much to be gained from the book even if you don't use any of these tools in your work.


## Intended Audience




 

